---
- hosts: all
  user: vagrant
  vars:
    data_dir: /vagrant_data
    shared_dir: /vagrant
  tasks:

  - name: Update repository information
    sudo: yes
    shell: apt-get update

  - name: Install general dependensies for Block
    sudo: yes
    apt: name="{{ item }}" state=present
    with_items:
      - git
      - libhdf5-serial-dev
      - libjpeg-dev
      - libfreetype6-dev
      - libpng-dev
      - python-dev
      - python-numpy
      - python-scipy
      - python-matplotlib

  - name: Install Python dependensies for Block
    sudo: yes
    pip: name="{{ item['name'] }}" version="{{ item['version'] }}"
    with_items:
      - name: Cython
        version: 0.22
      - name: six
        version: 1.9.0
      - name: pandas
        version: 0.16.1
      - name: progressbar2
        version: 2.7.3
      - name: PyYaml
        version: 3.11
      - name: toolz
        version: 0.7.2
      - name: picklable-itertools
        version: 0.1.0

  - name: Install Theano
    sudo: yes
    pip: name="git+https://github.com/Theano/Theano.git@c6d2ab3929182cdf7cf12e4b1f191a6ff99d07cc#egg=theano"

  - name: Install fuel
    sudo: yes
    pip: name="git+https://github.com/mila-udem/fuel@stable#egg=fuel"

  - name: Install Blocks
    sudo: yes
    # pip: name="git+git://github.com/mila-udem/blocks.git@stable" requirements="https://raw.githubusercontent.com/mila-udem/blocks/stable/requirements.txt"
    pip: name="git+git://github.com/mila-udem/blocks.git@stable#egg=blocks"

  # Setup IPython Notebook
  - name: Install IPython
    sudo: yes
    pip: name=ipython version=3.1.0

  - name: "Install requirements for IPython Notebook"
    sudo: yes
    pip: name="{{ item }}"
    with_items:
      - pyzmq
      - tornado
      - jinja2
      - jsonschema

  - name: Setting data path for fuel
    shell: "echo 'data_path: /vagrant_data' >> ~/.fuelrc"

  - name: Download MNIST
    sudo: yes
    shell: fuel-download mnist
    args:
      creates: "{{ data_dir }}/t10k-labels-idx1-ubyte.gz"

  - name: Translate MNIST
    sudo: yes
    shell: fuel-convert mnist
    args:
      creates: "{{ data_dir }}/mnist.hdf5"
